// <auto-generated />
using System;
using JuliaFlorea.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JuliaFlorea.DataModel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JuliaFlorea.DataModel.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.Depot", b =>
                {
                    b.Property<string>("DepotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepotAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageCapacity")
                        .HasColumnType("int");

                    b.HasKey("DepotId");

                    b.HasIndex("CountryId")
                        .IsUnique()
                        .HasFilter("[CountryId] IS NOT NULL");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.DrugType", b =>
                {
                    b.Property<string>("DrugTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DrugTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightInPounds")
                        .HasColumnType("float");

                    b.HasKey("DrugTypeId");

                    b.ToTable("DrugTypes");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.DrugUnit", b =>
                {
                    b.Property<string>("DrugUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepotId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DrugTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickNumber")
                        .HasColumnType("int");

                    b.HasKey("DrugUnitId");

                    b.HasIndex("DepotId");

                    b.HasIndex("DrugTypeId");

                    b.ToTable("DrugUnits");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiteId");

                    b.HasIndex("CountryCode");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.Depot", b =>
                {
                    b.HasOne("JuliaFlorea.DataModel.Country", "Country")
                        .WithOne("Depot")
                        .HasForeignKey("JuliaFlorea.DataModel.Depot", "CountryId");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.DrugUnit", b =>
                {
                    b.HasOne("JuliaFlorea.DataModel.Depot", "Depot")
                        .WithMany("DrugUnits")
                        .HasForeignKey("DepotId");

                    b.HasOne("JuliaFlorea.DataModel.DrugType", "DrugType")
                        .WithMany("DrugUnits")
                        .HasForeignKey("DrugTypeId");
                });

            modelBuilder.Entity("JuliaFlorea.DataModel.Site", b =>
                {
                    b.HasOne("JuliaFlorea.DataModel.Country", "Country")
                        .WithMany("Sites")
                        .HasForeignKey("CountryCode");
                });
#pragma warning restore 612, 618
        }
    }
}
